### ISSUE TITLE
Follower Count invalid

### ISSUE THREAD

**Issue by digantamisra98** [Theminijohn/quora-scraper#1]
Hi. Upon running the code, I'm getting for all entries, the follower count to be zero even when all entries have follower count > 0.
Also, it takes an html file as input, an htm file for input is giving error unless the webpage was saved in htm format.

**Comment by Theminijohn** [comment]
Hey @digantamisra98, Sorry, just saw this. I think you asked a question on SO as well and got it figured out? You didn't mention what the problem was in the end. If you're still having issues let me know.

As for the file extension, from a MAC, saving (<kbd>cmd</kbd> + <kbd>s</kbd>) the page downloads it to `input.htm`. If you're using another OS or want to change the file name and extension you can edit the code 🤘
